### PR TITLE
New format idea

### PR DESCRIPTION
**Pull request by eliassjogreen**

### CODE REVIEW

**Comment by pmdevita** [comment]
Oh wait no not yet I'm still experimenting. You had this set up a certain way and I don't want to just walk in and completely redo it, that would be unfair to you. Do you have any critiques for this idea?

**Comment by eliassjogreen** [comment]
Well some sorting would be good. Somethin like the [awesome lists](http://awesome.re) with a header with the thing it's doing like
```
## Gifs
* [a bot](Link to the bot.md file) - Description
## Videos
* [another one](Same here) - Description
 ```

**Comment by pmdevita** [comment]
How about this?

**Comment by eliassjogreen** [comment]
Looking good! Should we merge?

**Comment by pmdevita** [comment]
Sure I'll merge

**Pull request merged**
